[package]
name = "boatbomber/heatup"
description = "Why cool down when you can heat up? A Roblox Datastore wrapper that avoids the cooldown limit."
version = "0.1.5"
license = "MIT"
authors = ["boatbomber (https://boatbomber.com)"]
registry = "https://github.com/upliftgames/wally-index"
realm = "server"
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]
exclude = ["**"]

[dependencies]
HashLib = "boatbomber/hashlib@^1.0.0"
